# SVM(C) : Classification (Binary and Multiclass)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import joblib

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
df['target'] = data.target

In [8]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [9]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [10]:
df['target_names'] = df['target'].map({i:name for i, name in enumerate(data.target_names)})

In [11]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [12]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_names  
0       0       setosa  
1       0       setosa  
2       0       setosa  
3       0       setosa  
4       0       setosa

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [14]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

In [15]:
df['target_names'].value_counts()

target_names
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

## SVM(C) : Binary classification  

In [16]:
binary_df = df[df['target'] != 2]

In [17]:
X_binary = binary_df.drop(['target', 'target_names'], axis=1)

In [18]:
X_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [19]:
y_binary = binary_df['target']

In [20]:
y_binary

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_binary, y_binary, test_size=0.2, random_state=42)

In [22]:
X_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           80.00000         80.000000          80.000000   
mean             5.47250          3.075000           2.897500   
std              0.65429          0.470524           1.420107   
min              4.30000          2.000000           1.100000   
25%              5.00000          2.800000           1.500000   
50%              5.40000          3.000000           3.300000   
75%              5.92500          3.400000           4.300000   
max              7.00000          4.400000           4.900000   

       petal width (cm)  
count         80.000000  
mean           0.805000  
std            0.555046  
min            0.100000  
25%            0.200000  
50%            1.000000  
75%            1.300000  
max            1.600000

In [23]:
scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [24]:
X_train

array([[ 0.34989908, -0.5881428 ,  1.13555602,  0.89744481],
       [ 0.19609729, -0.16040258,  0.8521099 ,  0.89744481],
       [-0.72671348,  0.69507785, -0.91942835, -0.73427302],
       [-1.64952424,  0.26733764, -1.13201294, -1.09687699],
       [ 0.19609729, -1.22975312,  0.71038684,  0.53484084],
       [ 0.34989908,  2.83377893, -0.99028988, -0.73427302],
       [-0.72671348,  0.90894796, -1.13201294, -0.91557501],
       [ 0.34989908, -0.37427269,  0.92297143,  0.89744481],
       [-0.88051527,  0.05346753, -0.99028988, -1.27817897],
       [ 1.27270985, -1.22975312,  1.41900214,  1.26004877],
       [-1.03431707,  0.69507785, -0.91942835, -1.09687699],
       [-1.34192066,  0.26733764, -1.06115141, -1.09687699],
       [ 0.81130447,  0.69507785,  1.13555602,  1.44135075],
       [-0.41910989,  0.69507785, -1.06115141, -1.09687699],
       [-0.72671348, -1.65749334,  0.28521766,  0.35353886],
       [-0.1115063 ,  1.76442839, -0.84856682, -0.73427302],
       [ 0.19609729, -0.

In [25]:
svm_binary = SVC(kernel='linear', C=1.0, probability=True)

In [26]:
svm_binary.fit(X_train, y_train)

SVC(kernel='linear', probability=True)

In [27]:
y_pred = svm_binary.predict(X_test)

In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [29]:
confusion_matrix(y_test, y_pred)

array([[12,  0],
       [ 0,  8]])

In [30]:
to_save = {
    'model': svm_binary,
    'scaler': scalar
}

joblib.dump(to_save, 'svm(c)_binary_scalar.joblib')

['svm(c)_binary_scalar.joblib']

## SVM : Multiclass classification

In [31]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
145       2    virginica  
146       2    virginica  
147       2    virginica  
148       2    virginica  
149       2    virginica  

[150 rows x 6 columns]

In [32]:
X_multi = df.drop(['target', 'target_names'], axis=1)

In [33]:
X_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [34]:
y_multi = df['target']

In [35]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [36]:
X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

In [37]:
scalar_multi = StandardScaler()
X_train_multi = scalar_multi.fit_transform(X_train_multi)
X_test_multi = scalar_multi.transform(X_test_multi)

In [38]:
X_train_multi

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

In [39]:
svm_multi = SVC(kernel='linear')

In [40]:
svm_multi.fit(X_train_multi, y_train_multi)

SVC(kernel='linear')

In [41]:
y_pred_multi = svm_multi.predict(X_test_multi)

In [42]:
print(classification_report(y_test_multi, y_pred_multi))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [43]:
confusion_matrix(y_test_multi, y_pred_multi)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]])

In [44]:
to_save = {
    'model': svm_multi,
    'scaler': scalar_multi
}

joblib.dump(to_save, 'svm(c)_multi_scalar.joblib')

['svm(c)_multi_scalar.joblib']

# Logistic Regression : Classification (Binary and Multiclass)

In [45]:
# Binary data
X_train, X_test, y_train, y_test

(array([[ 0.34989908, -0.5881428 ,  1.13555602,  0.89744481],
        [ 0.19609729, -0.16040258,  0.8521099 ,  0.89744481],
        [-0.72671348,  0.69507785, -0.91942835, -0.73427302],
        [-1.64952424,  0.26733764, -1.13201294, -1.09687699],
        [ 0.19609729, -1.22975312,  0.71038684,  0.53484084],
        [ 0.34989908,  2.83377893, -0.99028988, -0.73427302],
        [-0.72671348,  0.90894796, -1.13201294, -0.91557501],
        [ 0.34989908, -0.37427269,  0.92297143,  0.89744481],
        [-0.88051527,  0.05346753, -0.99028988, -1.27817897],
        [ 1.27270985, -1.22975312,  1.41900214,  1.26004877],
        [-1.03431707,  0.69507785, -0.91942835, -1.09687699],
        [-1.34192066,  0.26733764, -1.06115141, -1.09687699],
        [ 0.81130447,  0.69507785,  1.13555602,  1.44135075],
        [-0.41910989,  0.69507785, -1.06115141, -1.09687699],
        [-0.72671348, -1.65749334,  0.28521766,  0.35353886],
        [-0.1115063 ,  1.76442839, -0.84856682, -0.73427302],
        

In [46]:
# Multi-class data
X_train_multi, X_test_multi, y_train_multi, y_test_multi

(array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
        [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
        [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
        [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
        [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
        [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
        [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
        [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
        [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
        [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
        [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
        [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
        [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
        [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
        [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
        [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
        

## Logistic Regression : Binary classification

In [47]:
from sklearn.linear_model import LogisticRegression

In [48]:
X_train

array([[ 0.34989908, -0.5881428 ,  1.13555602,  0.89744481],
       [ 0.19609729, -0.16040258,  0.8521099 ,  0.89744481],
       [-0.72671348,  0.69507785, -0.91942835, -0.73427302],
       [-1.64952424,  0.26733764, -1.13201294, -1.09687699],
       [ 0.19609729, -1.22975312,  0.71038684,  0.53484084],
       [ 0.34989908,  2.83377893, -0.99028988, -0.73427302],
       [-0.72671348,  0.90894796, -1.13201294, -0.91557501],
       [ 0.34989908, -0.37427269,  0.92297143,  0.89744481],
       [-0.88051527,  0.05346753, -0.99028988, -1.27817897],
       [ 1.27270985, -1.22975312,  1.41900214,  1.26004877],
       [-1.03431707,  0.69507785, -0.91942835, -1.09687699],
       [-1.34192066,  0.26733764, -1.06115141, -1.09687699],
       [ 0.81130447,  0.69507785,  1.13555602,  1.44135075],
       [-0.41910989,  0.69507785, -1.06115141, -1.09687699],
       [-0.72671348, -1.65749334,  0.28521766,  0.35353886],
       [-0.1115063 ,  1.76442839, -0.84856682, -0.73427302],
       [ 0.19609729, -0.

In [49]:
X_test

array([[ 0.81130447, -0.80201291,  1.5607252 ,  1.44135075],
       [ 0.04229549, -1.65749334,  0.78124837,  0.89744481],
       [ 0.65750267,  0.26733764,  1.34814061,  1.80395471],
       [-1.03431707, -0.16040258, -1.06115141, -0.91557501],
       [-0.57291168,  1.55055828, -0.70684376, -0.73427302],
       [-0.57291168,  0.69507785, -0.99028988, -1.09687699],
       [-1.34192066,  1.12281807, -1.34459753, -1.09687699],
       [ 0.04229549, -1.44362323,  0.63952531,  0.53484084],
       [-0.1115063 ,  1.33668818, -0.99028988, -1.09687699],
       [-0.57291168,  0.90894796, -1.06115141, -1.09687699],
       [ 0.34989908,  1.55055828, -0.84856682, -0.91557501],
       [-1.03431707,  0.05346753, -0.91942835, -1.09687699],
       [ 0.96510626, -0.5881428 ,  1.27727908,  0.71614283],
       [ 0.04229549,  2.40603872, -1.06115141, -1.09687699],
       [ 0.04229549, -1.01588301,  1.06469449,  0.71614283],
       [-0.72671348,  1.12281807, -1.06115141, -1.09687699],
       [ 2.04171882, -0.

In [50]:
logistics_binary = LogisticRegression()
logistics_binary.fit(X_train, y_train)


LogisticRegression()

In [51]:
y_pred = logistics_binary.predict(X_test)

In [52]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [53]:
confusion_matrix(y_test, y_pred)

array([[12,  0],
       [ 0,  8]])

In [54]:
to_save = {
    'model': logistics_binary,
    'scaler': scalar
}

joblib.dump(to_save, 'logistics_binary_scalar.joblib')

['logistics_binary_scalar.joblib']

## Logistic Regression : Multiclass classification (OVR)

In [55]:
X_train_multi

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.

In [56]:
X_test_multi

array([[ 0.35451684, -0.58505976,  0.55777524,  0.02224751],
       [-0.13307079,  1.65083742, -1.16139502, -1.17911778],
       [ 2.30486738, -1.0322392 ,  1.8185001 ,  1.49058286],
       [ 0.23261993, -0.36147005,  0.44316389,  0.4227026 ],
       [ 1.2077952 , -0.58505976,  0.61508092,  0.28921757],
       [-0.49876152,  0.75647855, -1.27600637, -1.04563275],
       [-0.2549677 , -0.36147005, -0.07258719,  0.15573254],
       [ 1.32969211,  0.08570939,  0.78699794,  1.49058286],
       [ 0.47641375, -1.92659808,  0.44316389,  0.4227026 ],
       [-0.01117388, -0.80864948,  0.09932984,  0.02224751],
       [ 0.84210448,  0.30929911,  0.78699794,  1.09012776],
       [-1.23014297, -0.13788033, -1.33331205, -1.44608785],
       [-0.37686461,  0.98006827, -1.39061772, -1.31260282],
       [-1.10824606,  0.08570939, -1.27600637, -1.44608785],
       [-0.86445224,  1.65083742, -1.27600637, -1.17911778],
       [ 0.59831066,  0.53288883,  0.55777524,  0.55618763],
       [ 0.84210448, -0.

In [57]:
logistics_ovr = LogisticRegression(multi_class='ovr', solver='lbfgs', max_iter=2000)

In [58]:
logistics_ovr.fit(X_train_multi, y_train_multi)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [59]:
y_pred_multi_ovr = logistics_ovr.predict(X_test_multi)

In [60]:
print(classification_report(y_test_multi, y_pred_multi))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [61]:
confusion_matrix(y_test_multi, y_pred_multi)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]])

In [62]:
to_save = {
    'model': logistics_ovr,
    'scaler': scalar_multi
}

joblib.dump(to_save, 'logistics_ovr_multi_scalar.joblib')

['logistics_ovr_multi_scalar.joblib']

## Logistic Regression : Multiclass classification (Multinomial/Softmax)

In [63]:
logistics_multinomial = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=2000)

In [64]:
logistics_multinomial.fit(X_train_multi, y_train_multi)

c:\Users\ADMIN\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [65]:
y_pred_multi_multinomial = logistics_multinomial.predict(X_test_multi)

In [66]:
print(classification_report(y_test_multi, y_pred_multi_multinomial))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [67]:
confusion_matrix(y_test_multi, y_pred_multi_multinomial)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [68]:
to_save = {
    'model': logistics_multinomial,
    'scaler': scalar_multi
}

joblib.dump(to_save, 'logistics_multinomial_multi_scalar.joblib')

['logistics_multinomial_multi_scalar.joblib']